import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "斜杠转换",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* 使用 Tailwind 定义的 font-sans / font-mono，已从 CSS 变量绑定 */}
      <body className="antialiased font-sans">
        {children}
      </body>
    </html>
  );
}
